---
title: Le pot de depang
baseURL: "/"
params:
  palette: blue
  header:
    title: Le pot de d√©pang
    tagline: ''
    logo_img: images/logo.png
    bg_img: "/images/contact.jpg"
    has_nav: true
    has_social: false
  footer:
    content: "&copy; All rights reserved."
    links:
    - text: Made with Stackbit
      url: https://www.stackbit.com
      new_window: true
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
menu:
  main:
  - name: Le coin des complotistes
    weight: 8
  - name: Blind Test
    weight: 7
